#include<stdio.h>
#include<stdlib.h>
#include<time.h>

void menu();
void level();
void delay(float sec);
void animation();
void main()
{
menu();

}
void menu()
{
int a;
printf("\n\n\n\n\n\n");
printf("\t\t\t\t______________\n");
printf("\t\t\t\t|1.Start Game|\n");
printf("\t\t\t\t|2.   Level  |\n");
printf("\t\t\t\t|3.   Exit   |\n");
printf("\t\t\t\t|____________|\n");
scanf("%d",&a);

switch(a)
{
case 1:
animation();
break;
case 2:
level();
break;
case 3:
system("cls");
exit(1);
break;


}

}
void level()
{
int l;
system("cls");
printf("\n\n\n\n\n\n");
printf("\t\t\t\t______________\n");
printf("\t\t\t\t|1.   Easy   |\n");
printf("\t\t\t\t|2.  Medium  |\n");
printf("\t\t\t\t|3.   Hard   |\n");
printf("\t\t\t\t|____________|\n");
scanf("%d",&l);
switch(l)
{
case 1:
printf("Easy mode");
break;

}
}
void delay(float sec)
{
    // Converting time into milli_seconds
    int milli_seconds = 1000 * sec;
 
    // Storing start time
    clock_t start_time = clock();
 
    // looping till required time is not achieved
    while (clock() < start_time + milli_seconds)
        ;

    /* This Piece of code Was Taken from stackoverflow.com */
}
void animation()
{

		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )\n");
		printf("\t\t\t| O  O |\n");
		printf("\t\t\t|  ()  | \n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.5);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )\n");
		printf("\t\t\t| -  - |\n");
		printf("\t\t\t|  ()  | \n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )\n");
		printf("\t\t\t| O  O |\n");
		printf("\t\t\t|  ()  | \n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.5);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )\n");
		printf("\t\t\t| -  - |\n");
		printf("\t\t\t|  ()  | \n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )\n");
		printf("\t\t\t| O  O |\n");
		printf("\t\t\t|  ()  | \n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.5);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )\n");
		printf("\t\t\t| -  - |\n");
		printf("\t\t\t|  ()  | \n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.5);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )\n");
		printf("\t\t\t| O  O |\n");
		printf("\t\t\t|  ()  |\n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.5);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )\n");
		printf("\t\t\t| O  O |\n");
		printf("\t\t\t|  ()  |\n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.5);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )\n");
		printf("\t\t\t| >  < |\n");
		printf("\t\t\t|0 () 0| \n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.5);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )\n");
		printf("\t\t\t| >  < |\n");
		printf("\t\t\t|o  3 o| \n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      ) _ _\n");
		printf("\t\t\t| >  < |( v )\n");
		printf("\t\t\t|o  3 o|  V\n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______   _ _\n");
		printf("\t\t\t(      ) ( v )\n");
		printf("\t\t\t| >  < |   V\n");
		printf("\t\t\t|o  3 o|    \n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )   _ _\n");
		printf("\t\t\t| >  < |  ( v )\n");
		printf("\t\t\t|o  3 o|    V\n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______     _ _\n");
		printf("\t\t\t(      )   ( v )\n");
		printf("\t\t\t| >  < |     V\n");
		printf("\t\t\t|o  3 o|      \n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )     _ _\n");
		printf("\t\t\t| >  < |    ( v )\n");
		printf("\t\t\t|o  3 o|      V\n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )      _ _\n");
		printf("\t\t\t| >  < |     ( v )\n");
		printf("\t\t\t|o  3 o|       V\n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )       _ _\n");
		printf("\t\t\t| >  < |      ( v )\n");
		printf("\t\t\t|o  3 o|        V\n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )      _ _\n");
		printf("\t\t\t| >  < |     - v -\n");
		printf("\t\t\t|o  3 o|       |\n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.1);
		system("cls");
	
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )      \n");
		printf("\t\t\t| >  < |       *\n");
		printf("\t\t\t|o  3 o|      \n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.5);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )       |\n");
		printf("\t\t\t| >  < |      -O-\n");
		printf("\t\t\t|o  3 o|       |\n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )\n");
		printf("\t\t\t| O  O |\n");
		printf("\t\t\t|  ()  |\n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.5);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t ______\n");
		printf("\t\t\t(      )\n");
		printf("\t\t\t| O  O |\n");
		printf("\t\t\t|  ()  |\n");
		printf("\t\t\t|------|\n");
		printf("\t\t\t  U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t  ______\n");
		printf("\t\t\t (      )\n");
		printf("\t\t\t | O  O |\n");
		printf("\t\t\t |  ()  |\n");
		printf("\t\t\t |------|\n");
		printf("\t\t\t   U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t  | O  O |\n");
		printf("\t\t\t  |  ()  |\n");
		printf("\t\t\t  |------|\n");
		printf("\t\t\t    U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t    ______\n");
		printf("\t\t\t   (      )\n");
		printf("\t\t\t   | O  O |\n");
		printf("\t\t\t   |  ()  |\n");
		printf("\t\t\t   |------|\n");
		printf("\t\t\t     U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t     ______\n");
		printf("\t\t\t    (      )\n");
		printf("\t\t\t    | O  O |\n");
		printf("\t\t\t    |  ()  |\n");
		printf("\t\t\t    |------|\n");
		printf("\t\t\t      U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t      ______\n");
		printf("\t\t\t     (      )\n");
		printf("\t\t\t     | O  O |\n");
		printf("\t\t\t     |  ()  |\n");
		printf("\t\t\t     |------|\n");
		printf("\t\t\t       U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t       ______\n");
		printf("\t\t\t      (      )\n");
		printf("\t\t\t      | O  O |\n");
		printf("\t\t\t      |  ()  |\n");
		printf("\t\t\t      |------|\n");
		printf("\t\t\t        U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t         ______\n");
		printf("\t\t\t        (      )\n");
		printf("\t\t\t        | O  O |\n");
		printf("\t\t\t        |  ()  |\n");
		printf("\t\t\t        |------|\n");
		printf("\t\t\t          U  U \n");
		delay(0.5);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t         ______\n");
		printf("\t\t\t        (      )\n");
		printf("\t\t\t        | -  - |\n");
		printf("\t\t\t        |  ()  |\n");
		printf("\t\t\t        |------|\n");
		printf("\t\t\t          U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t         ______\n");
		printf("\t\t\t        (      )\n");
		printf("\t\t\t        | O  O |\n");
		printf("\t\t\t        |  ()  |\n");
		printf("\t\t\t        |------|\n");
		printf("\t\t\t          U  U \n");
		delay(0.5);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t         ______\n");
		printf("\t\t\t        (      )\n");
		printf("\t\t\t        | -  - |\n");
		printf("\t\t\t        |  ()  |\n");
		printf("\t\t\t        |------|\n");
		printf("\t\t\t          U  U \n");
		delay(0.1);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t         ______\n");
		printf("\t\t\t        (      )\n");
		printf("\t\t\t        | O  O |\n");
		printf("\t\t\t        |  ()  |\n");
		printf("\t\t\t        |------|\n");
		printf("\t\t\t          U  U \n");
		delay(0.5);
		system("cls");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t         ______\n");
		printf("\t\t\t        (      )\n");
		printf("\t\t\t        | O  O |\n");
		printf("\t\t\t        |  ()  |\n");
		printf("\t\t\t        |------|\n");
		printf("\t\t\t          U  U \n");
		delay(0.5);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tH");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tW");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWe");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWel");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelc");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelco");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcom");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome ");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome M");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.S");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sa");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Saj");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sajj");
		delay(0.3);
		system("cls");printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sajji");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sajjit");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sajjit.");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sajjit..");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sajjit...");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sajjit");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sajjit.");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sajjit..");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sajjit...");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sajjit");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sajjit.");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sajjit..");
		delay(0.3);
		system("cls");
		printf("\n\n\n\n\n\n\n\n\n");
		printf("\t\t\t\tHi!\n\n\t\t\tWelcome Mr.Sajjit...");
		delay(0.3);
		system("cls");
		}
