#include<stdio.h>
#include<stdlib.h>
#include<time.h>

void delayopp(float sec);

void animation()
   {
   		
		printf("\n");
		printf("\t\t\t   O");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Ou");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our T");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Te");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Tea");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| o__o |__\n");
		printf("\t\t\t| |______| |\n");
		printf("\t\t\t|_|      |_|\n");
		printf("\t\t\t U|--()--|U\n");
		printf("\t\t\t  |__||__|\n");
		printf("\t\t\t   U    U \n");
		delayopp(0.5);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| -__- |__\n");
		printf("\t\t\t| |______| |\n");
		printf("\t\t\t|_|      |_|\n");
		printf("\t\t\t U|--()--|U\n");
		printf("\t\t\t  |__||__|\n");
		printf("\t\t\t   U    U \n");
		delayopp(0.5);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| o__o |__\n");
		printf("\t\t\t| |______| |\n");
		printf("\t\t\t|_|      |_|\n");
		printf("\t\t\t U|--()--|U\n");
		printf("\t\t\t  |__||__|\n");
		printf("\t\t\t   U    U \n");
		delayopp(0.5);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| -__- |__\n");
		printf("\t\t\t| |______| |\n");
		printf("\t\t\t|_|      |_|\n");
		printf("\t\t\t U|--()--|U\n");
		printf("\t\t\t  |__||__|\n");
		printf("\t\t\t   U    U \n");
		delayopp(0.5);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| o__o |__\n");
		printf("\t\t\t| |______| |\n");
		printf("\t\t\t|_|      |_|\n");
		printf("\t\t\t U|--()--|U\n");
		printf("\t\t\t  |__||__|\n");
		printf("\t\t\t   U    U \n");
		delayopp(0.5);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| -__- |__\n");
		printf("\t\t\t| |______| |\n");
		printf("\t\t\t|_|      |_|\n");
		printf("\t\t\t U|--()--|U\n");
		printf("\t\t\t  |__||__|\n");
		printf("\t\t\t   U    U \n");
		delayopp(0.5);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| o__o |__        |- \n");
		printf("\t\t\t| |______| |  -------  -\n");
		printf("\t\t\t|_|      |_|             -\n");
		printf("\t\t\t U|--()--|U   -------  -\n");
		printf("\t\t\t  |__||__|          |-\n");
		printf("\t\t\t   U    U \n");
		delayopp(0.5);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| o__o |__        |- \n");
		printf("\t\t\t| |______| |  -------  -\n");
		printf("\t\t\t|_|      |_|             -\n");
		printf("\t\t\t U|--()--|U   -------  -\n");
		printf("\t\t\t  |__||__|          |-\n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| o__o |__        |-    \n");
		printf("\t\t\t| |______| |  -------  -      \n");
		printf("\t\t\t|__|>  <|__|             -  S      \n");
		printf("\t\t\t  |--()--|    -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| o__o |__        |-    \n");
		printf("\t\t\t| |______| |  -------  -     \n");
		printf("\t\t\t|_|      |_|             -  Sa     \n");
		printf("\t\t\t U|--()--|U   -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| o__o |__        |-    \n");
		printf("\t\t\t| |______| |  -------  -      \n");
		printf("\t\t\t|__|>  <|__|             -  Say      \n");
		printf("\t\t\t  |--()--|    -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| o__o |__        |-    \n");
		printf("\t\t\t| |______| |  -------  -     \n");
		printf("\t\t\t|_|      |_|             -  Sayu     \n");
		printf("\t\t\t U|--()--|U   -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| o__o |__        |-    \n");
		printf("\t\t\t| |______| |  -------  -      \n");
		printf("\t\t\t|__|>  <|__|             -  Sayuj      \n");
		printf("\t\t\t  |--()--|    -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| o__o |__        |-    \n");
		printf("\t\t\t| |______| |  -------  -     \n");
		printf("\t\t\t|_|      |_|             -  Sayujy     \n");
		printf("\t\t\t U|--()--|U   -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);
		system("cls");printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| o__o |__        |-    \n");
		printf("\t\t\t| |______| |  -------  -      \n");
		printf("\t\t\t|__|>  <|__|             -  Sayujya      \n");
		printf("\t\t\t  |--()--|    -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);

		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  (      )\n");
		printf("\t\t\t__| o__o |__        |-    \n");
		printf("\t\t\t| |______| |  -------  -     \n");
		printf("\t\t\t|_|      |_|             -  Sayujya     \n");
		printf("\t\t\t U|--()--|U   -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(1);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  || |||||\n");
		printf("\t\t\t__-(o)_(o)__      \n");
		printf("\t\t\t| |______| |      \n");
		printf("\t\t\t|_|      |_|      \n");
		printf("\t\t\t U|--()--|U       \n");
		printf("\t\t\t  |__||__|        \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  || |||||\n");
		printf("\t\t\t__-(-)_(-)__      \n");
		printf("\t\t\t| |______| |      \n");
		printf("\t\t\t|_|      |_|      \n");
		printf("\t\t\t U|--()--|U       \n");
		printf("\t\t\t  |__||__|        \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.5);
		system("cls");
			printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  || |||||\n");
		printf("\t\t\t__-(o)_(o)__      \n");
		printf("\t\t\t| |______| |      \n");
		printf("\t\t\t|_|      |_|      \n");
		printf("\t\t\t U|--()--|U       \n");
		printf("\t\t\t  |__||__|        \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.5);
		system("cls");
			printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  || |||||\n");
		printf("\t\t\t__-(-)_(-)__      \n");
		printf("\t\t\t| |______| |      \n");
		printf("\t\t\t|_|      |_|      \n");
		printf("\t\t\t U|--()--|U       \n");
		printf("\t\t\t  |__||__|        \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.5);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  || |||||\n");
		printf("\t\t\t__-(o)_(o)__        |-    \n");
		printf("\t\t\t| |______| |  -------  -    \n");
		printf("\t\t\t|_|      |_|             -  \n");
		printf("\t\t\t U|--()--|U   -------  -    \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);
		system("cls");
			printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  || |||||\n");
		printf("\t\t\t__-(o)_(o)__        |-    \n");
		printf("\t\t\t| |______| |  -------  -      \n");
		printf("\t\t\t|_|      |_|             -   S    \n");
		printf("\t\t\t U|--()--|U   -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);
		system("cls");
			printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t   ______\n");
		printf("\t\t\t  || |||||\n");
		printf("\t\t\t__-(o)_(o)__        |-    \n");
		printf("\t\t\t| |______| |  -------  -      \n");
		printf("\t\t\t|_|      |_|             -  Sa    \n");
		printf("\t\t\t U|--()--|U   -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);
		system("cls");
			printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
	
		printf("\t\t\t   ______\n");
		printf("\t\t\t  || |||||\n");
		printf("\t\t\t__-(o)_(<)__        |-    \n");
		printf("\t\t\t| |______| |  -------  -      \n");
		printf("\t\t\t|_|      |_|             -  Sar   \n");
		printf("\t\t\t U|--()--|U   -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);
		system("cls");
			printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		
		printf("\t\t\t   ______\n");
		printf("\t\t\t  || |||||\n");
		printf("\t\t\t__-(o)_(<)__        |-    \n");
		printf("\t\t\t| |______| |  -------  -      \n");
		printf("\t\t\t|_|      |_|             -  Sari  \n");
		printf("\t\t\t U|--()--|U   -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);
		system("cls");
			printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		
		printf("\t\t\t   ______\n");
		printf("\t\t\t  || |||||\n");
		printf("\t\t\t__-(o)_(<)__        |-    \n");
		printf("\t\t\t| |______| |  -------  -      \n");
		printf("\t\t\t|_|      |_|             -  Sarin \n");
		printf("\t\t\t U|--()--|U   -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.3);
	
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
	
		printf("\t\t\t   ______\n");
		printf("\t\t\t  || |||||\n");
		printf("\t\t\t__-(o)_(o)__        |-    \n");
		printf("\t\t\t| |______| |  -------  -      \n");
		printf("\t\t\t|_|      |_|             -  Sarin \n");
		printf("\t\t\t U|--()--|U   -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(1);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t__||o _o||__      \n");
		printf("\t\t\t| |______| |      \n");
		printf("\t\t\t|_|      |_|      \n");
		printf("\t\t\t U|--()--|U       \n");
		printf("\t\t\t  |__||__|        \n");
		printf("\t\t\t   U    U         \n");
		delayopp(0.5);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t__||- _-||__      \n");
		printf("\t\t\t| |______| |      \n");
		printf("\t\t\t|_|      |_|      \n");
		printf("\t\t\t U|--()--|U       \n");
		printf("\t\t\t  |__||__|        \n");
		printf("\t\t\t   U    U         \n");
		delayopp(0.5);
		system("cls");
			printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t__||o _o||__      \n");
		printf("\t\t\t| |______| |      \n");
		printf("\t\t\t|_|      |_|      \n");
		printf("\t\t\t U|--()--|U       \n");
		printf("\t\t\t  |__||__|        \n");
		printf("\t\t\t   U    U         \n");
		delayopp(0.5);
		system("cls");
			printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t__||- _-||__      \n");
		printf("\t\t\t| |______| |      \n");
		printf("\t\t\t|_|      |_|      \n");
		printf("\t\t\t U|--()--|U       \n");
		printf("\t\t\t  |__||__|        \n");
		printf("\t\t\t   U    U         \n");
		delayopp(0.5);
		system("cls");
			printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t__||o _o||__      \n");
		printf("\t\t\t| |______| |      \n");
		printf("\t\t\t|_|      |_|      \n");
		printf("\t\t\t U|--()--|U       \n");
		printf("\t\t\t  |__||__|        \n");
		printf("\t\t\t   U    U         \n");
		delayopp(0.5);
		system("cls");
			printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
	
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t__||- _-||__      \n");
		printf("\t\t\t| |______| |      \n");
		printf("\t\t\t|_|      |_|      \n");
		printf("\t\t\t U|--()--|U       \n");
		printf("\t\t\t  |__||__|        \n");
		printf("\t\t\t   U    U         \n");
		delayopp(0.5);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");

		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t__||o _o||__        |-   \n");
		printf("\t\t\t| |______| |  -------  -    \n");
		printf("\t\t\t|_|      |_|             -  \n");
		printf("\t\t\t U|--()--|U   -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.5);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t__||o _o||__        |-    \n");
		printf("\t\t\t| |______| |  -------  -      \n");
		printf("\t\t\t|_|      |U              -  S  \n");
		printf("\t\t\t U|--()--|    -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.2);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
	
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t__||o _o||__        |-    \n");
		printf("\t\t\t| |______|M|  -------  -      \n");
		printf("\t\t\t|_|      |-               -  Sa  \n");
		printf("\t\t\t U|--()--|    -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.2);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@M\n");
		printf("\t\t\t__||o _o|| |        |-    \n");
		printf("\t\t\t| |______|_|  -------  -     \n");
		printf("\t\t\t|_|      |               -  Saj\n"); 
		printf("\t\t\t U|--()--|    -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.2);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
	
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@ M\n");
		printf("\t\t\t__||o _o||/ /       |-    \n");
		printf("\t\t\t| |______|_/  -------  -      \n");
		printf("\t\t\t|_|      |               -  Sajj\n");
		printf("\t\t\t U|--()--|    -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.2);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@M\n");
		printf("\t\t\t__||o _o|| |        |-    \n");
		printf("\t\t\t| |______|_|  -------  -     \n");
		printf("\t\t\t|_|      |               -  Sajji\n"); 
		printf("\t\t\t U|--()--|    -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.2);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
	
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@ M\n");
		printf("\t\t\t__||o _o||/ /       |-    \n");
		printf("\t\t\t| |______|_/  -------  -      \n");
		printf("\t\t\t|_|      |               -  Sajjit\n");
		printf("\t\t\t U|--()--|    -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.2);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@M\n");
		printf("\t\t\t__||o _o|| |        |-    \n");
		printf("\t\t\t| |______|_|  -------  -     \n");
		printf("\t\t\t|_|      |               -  Sajjit\n"); 
		printf("\t\t\t U|--()--|    -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.2);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
	
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t__||o _o||__        |-    \n");
		printf("\t\t\t| |______|M|  -------  -      \n");
		printf("\t\t\t|_|      |-               -  Sajjit  \n");
		printf("\t\t\t U|--()--|    -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.2);
	
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");
		
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t__||o _o||__        |-    \n");
		printf("\t\t\t| |______| |  -------  -      \n");
		printf("\t\t\t|_|      |U              -  Sajjit  \n");
		printf("\t\t\t U|--()--|    -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(0.2);
		system("cls");
		printf("\n");
		printf("\t\t\t   Our Team!!!");
		printf("\n\n\n\n\n\n");

		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t  @@@@@@@@\n");
		printf("\t\t\t__||o _o||__        |-   \n");
		printf("\t\t\t| |______| |  -------  -    \n");
		printf("\t\t\t|_|      |_|             -  Sajjit\n");
		printf("\t\t\t U|--()--|U   -------  -     \n");
		printf("\t\t\t  |__||__|          |-      \n");
		printf("\t\t\t   U    U \n");
		delayopp(1);
		system("cls");
		//3 men greeting
		printf("\n\n\n");
		printf("\t[1].Sayujya    [2].Sajjit    [3].Sarin            \n\n");
		printf("\t   ______       @@@@@@@@        ______                \n");
		printf("\t  (      )      @@@@@@@@       || |||||                      \n");
		printf("\t__| o__o |__  __||o _o||__   __-(o)_(o)__                    \n");
		printf("\t| |______| |  | |______| |   | |______| |                     \n");
		printf("\t|_|      |_|  |_|      |_|   |_|      |_|                    \n");
		printf("\t U|--()--|U    U|--()--|U     U|--()--|U                   \n");
		printf("\t  |__||__|      |__||__|       |__||__|                 \n");
		printf("\t   U    U        U    U         U    U                \n");
		printf("\n\n\n");
		printf(" **************************************************\n");
		printf(" |                                                |\n");
		printf(" **************************************************\n");
		delayopp(0.2);
		system("cls");
		//3 men greeting
		printf("\n\n\n");
		printf("\t[1].Sayujya    [2].Sajjit    [3].Sarin            \n\n");
		printf("\t   ______       @@@@@@@@        ______                \n");
		printf("\t  (      )      @@@@@@@@       || |||||                      \n");
		printf("\t__| -__- |__  __||o _o||__   __-(o)_(o)__                    \n");
		printf("\t| |______| |  | |______| |   | |______| |                     \n");
		printf("\t|_|      |_|  |_|      |_|   |_|      |_|                    \n");
		printf("\t U|--()--|U    U|--()--|U     U|--()--|U                   \n");
		printf("\t  |__||__|      |__||__|       |__||__|                 \n");
		printf("\t   U    U        U    U         U    U                \n");
		printf("\n\n\n");
		printf(" **************************************************\n");
		printf(" |                T                               |\n");
		printf(" **************************************************\n");
		delayopp(0.2);
		system("cls");
		//3 men greeting
		printf("\n\n\n");
		printf("\t[1].Sayujya    [2].Sajjit    [3].Sarin            \n\n");
		printf("\t   ______       @@@@@@@@        ______                \n");
		printf("\t  (      )      @@@@@@@@       || |||||                      \n");
		printf("\t__| o__o |__  __||- _-||__   __-(o)_(o)__                    \n");
		printf("\t| |______| |  | |______| |   | |______| |                     \n");
		printf("\t|_|      |_|  |_|      |_|   |_|      |_|                    \n");
		printf("\t U|--()--|U    U|--()--|U     U|--()--|U                   \n");
		printf("\t  |__||__|      |__||__|       |__||__|                 \n");
		printf("\t   U    U        U    U         U    U                \n");
		printf("\n\n\n");
		printf(" **************************************************\n");
		printf(" |                TH                              |\n");
		printf(" **************************************************\n");
		delayopp(0.2);
		system("cls");
			printf("\n\n\n");
		printf("\t[1].Sayujya    [2].Sajjit    [3].Sarin            \n\n");
		printf("\t   ______       @@@@@@@@        ______                \n");
		printf("\t  (      )      @@@@@@@@       || |||||                      \n");
		printf("\t__| o__o |__  __||o _o||__   __-(-)_(-)__                    \n");
		printf("\t| |______| |  | |______| |   | |______| |                     \n");
		printf("\t|_|      |_|  |_|      |_|   |_|      |_|                    \n");
		printf("\t U|--()--|U    U|--()--|U     U|--()--|U                   \n");
		printf("\t  |__||__|      |__||__|       |__||__|                 \n");
		printf("\t   U    U        U    U         U    U                \n");
		printf("\n\n\n");
		printf(" **************************************************\n");
		printf(" |                THA                             |\n");
		printf(" **************************************************\n");
		delayopp(0.2);
		system("cls");
		//3 men greeting
		printf("\n\n\n");
		printf("\t[1].Sayujya    [2].Sajjit    [3].Sarin            \n\n");
		printf("\t   ______       @@@@@@@@        ______                \n");
		printf("\t  (      )      @@@@@@@@       || |||||                      \n");
		printf("\t__| -__- |__  __||o _o||__   __-(o)_(o)__                    \n");
		printf("\t| |______| |  | |______| |   | |______| |                     \n");
		printf("\t|_|      |_|  |_|      |_|   |_|      |_|                    \n");
		printf("\t U|--()--|U    U|--()--|U     U|--()--|U                   \n");
		printf("\t  |__||__|      |__||__|       |__||__|                 \n");
		printf("\t   U    U        U    U         U    U                \n");
		printf("\n\n\n");
		printf(" **************************************************\n");
		printf(" |                THAN                            |\n");
		printf(" **************************************************\n");
		delayopp(0.2);
		system("cls");
			printf("\n\n\n");
		printf("\t[1].Sayujya    [2].Sajjit    [3].Sarin            \n\n");
		printf("\t   ______       @@@@@@@@        ______                \n");
		printf("\t  (      )      @@@@@@@@       || |||||                      \n");
		printf("\t__| o__o |__  __||- _-||__   __-(o)_(o)__                    \n");
		printf("\t| |______| |  | |______| |   | |______| |                     \n");
		printf("\t|_|      |_|  |_|      |_|   |_|      |_|                    \n");
		printf("\t U|--()--|U    U|--()--|U     U|--()--|U                   \n");
		printf("\t  |__||__|      |__||__|       |__||__|                 \n");
		printf("\t   U    U        U    U         U    U                \n");
		printf("\n\n\n");
		printf(" **************************************************\n");
		printf(" |                THANK                           |\n");
		printf(" **************************************************\n");
		delayopp(0.2);
		system("cls");
		//3 men greeting
		printf("\n\n\n");
		printf("\t[1].Sayujya    [2].Sajjit    [3].Sarin            \n\n");
		printf("\t   ______       @@@@@@@@        ______                \n");
		printf("\t  (      )      @@@@@@@@       || |||||                      \n");
		printf("\t__| o__o |__  __||o _o||__   __-(-)_(-)__                    \n");
		printf("\t| |______| |  | |______| |   | |______| |                     \n");
		printf("\t|_|      |_|  |_|      |_|   |_|      |_|                    \n");
		printf("\t U|--()--|U    U|--()--|U     U|--()--|U                   \n");
		printf("\t  |__||__|      |__||__|       |__||__|                 \n");
		printf("\t   U    U        U    U         U    U                \n");
		printf("\n\n\n");
		printf(" **************************************************\n");
		printf(" |                THANK Y                         |\n");
		printf(" **************************************************\n");
		delayopp(0.2);
		system("cls");
			printf("\n\n\n");
		printf("\t[1].Sayujya    [2].Sajjit    [3].Sarin            \n\n");
		printf("\t   ______       @@@@@@@@        ______                \n");
		printf("\t  (      )      @@@@@@@@       || |||||                      \n");
		printf("\t__| -__- |__  __||- _-||__   __-(o)_(o)__                    \n");
		printf("\t| |______| |  | |______| |   | |______| |                     \n");
		printf("\t|_|      |_|  |_|      |_|   |_|      |_|                    \n");
		printf("\t U|--()--|U    U|--()--|U     U|--()--|U                   \n");
		printf("\t  |__||__|      |__||__|       |__||__|                 \n");
		printf("\t   U    U        U    U         U    U                \n");
		printf("\n\n\n");
		printf(" **************************************************\n");
		printf(" |                THANK YO                        |\n");
		printf(" **************************************************\n");
		delayopp(0.2);
		system("cls");
		//3 men greeting
		printf("\n\n\n");
		printf("\t[1].Sayujya    [2].Sajjit    [3].Sarin            \n\n");
		printf("\t   ______       @@@@@@@@        ______                \n");
		printf("\t  (      )      @@@@@@@@       || |||||                      \n");
		printf("\t__| o__o |__  __||o _o||__   __-(o)_(o)__                    \n");
		printf("\t| |______| |  | |______| |   | |______| |                     \n");
		printf("\t|_|      |_|  |_|      |_|   |_|      |_|                    \n");
		printf("\t U|--()--|U    U|--()--|U     U|--()--|U                   \n");
		printf("\t  |__||__|      |__||__|       |__||__|                 \n");
		printf("\t   U    U        U    U         U    U                \n");
		printf("\n\n\n");
		printf(" **************************************************\n");
		printf(" |                THANK YOU                       |\n");
		printf(" **************************************************\n");
		delayopp(0.2);
		system("cls");	
		printf("\n\n\n");
		printf("\t[1].Sayujya    [2].Sajjit    [3].Sarin            \n\n");
		printf("\t   ______       @@@@@@@@        ______                \n");
		printf("\t  (      )      @@@@@@@@       || |||||                      \n");
		printf("\t__| -__- |__  __||- _-||__   __-(-)_(-)__                    \n");
		printf("\t| |______| |  | |______| |   | |______| |                     \n");
		printf("\t|_|      |_|  |_|      |_|   |_|      |_|                    \n");
		printf("\t U|--()--|U    U|--()--|U     U|--()--|U                   \n");
		printf("\t  |__||__|      |__||__|       |__||__|                 \n");
		printf("\t   U    U        U    U         U    U                \n");
		printf("\n\n\n");
		printf(" **************************************************\n");
		printf(" |                THANK YOU!                      |\n");
		printf(" **************************************************\n");
		delayopp(0.2);
		system("cls");
		//3 men greeting
		printf("\n\n\n");
		printf("\t[1].Sayujya    [2].Sajjit    [3].Sarin            \n\n");
		printf("\t   ______       @@@@@@@@        ______                \n");
		printf("\t  (      )      @@@@@@@@       || |||||                      \n");
		printf("\t__| o__o |__  __||o _o||__   __-(o)_(o)__                    \n");
		printf("\t| |______| |  | |______| |   | |______| |                     \n");
		printf("\t|_|      |_|  |_|      |_|   |_|      |_|                    \n");
		printf("\t U|--()--|U    U|--()--|U     U|--()--|U                   \n");
		printf("\t  |__||__|      |__||__|       |__||__|                 \n");
		printf("\t   U    U        U    U         U    U                \n");
		printf("\n\n\n");
		printf(" **************************************************\n");
		printf(" |                THANK YOU!!                     |\n");
		printf(" **************************************************\n");
		delayopp(0.2);
		system("cls");
		//3 men greeting
		printf("\n\n\n");
		printf("\t[1].Sayujya    [2].Sajjit    [3].Sarin            \n\n");
		printf("\t   ______       @@@@@@@@        ______                \n");
		printf("\t  (      )      @@@@@@@@       || |||||                      \n");
		printf("\t__| o__o |__  __||o _o||__   __-(o)_(o)__                    \n");
		printf("\t| |______| |  | |______| |   | |______| |                     \n");
		printf("\t|_|      |_|  |_|      |_|   |_|      |_|                    \n");
		printf("\t U|--()--|U    U|--()--|U     U|--()--|U                   \n");
		printf("\t  |__||__|      |__||__|       |__||__|                 \n");
		printf("\t   U    U        U    U         U    U                \n");
		printf("\n\n\n");
		printf(" **************************************************\n");
		printf(" |                THANK YOU!!                     |\n");
		printf(" **************************************************\n");

		system("pause");
	}

void delayopp(float sec)
{
    // Converting time into milli_seconds
    int milli_seconds = 1000 * sec;
 
    // Storing start time
    clock_t start_time = clock();
 
    // looping till required time is not achieved
    while (clock() < start_time + milli_seconds)
        ;

    /* This Piece of code Was Taken from stackoverflow.com */
}